### PR TITLE
Bump Guzzle to ^7.0.1 and PHP to ^7.3

### PR DESCRIPTION
**Pull request by ishanAhuja**
This enables compatibility with Laravel 8.

### CODE REVIEW

**Comment by sudkumar** [comment]
@ishanAhuja  Thank you for the PR.

I think dropping the PHP support will be a breaking change which we can avoid. Laravel 8 requires `guzzlehttp/guzzle` to be `^7.0.1` which you have updated correctly. 

We have Laravel specific package [msg91-laravel](https://github.com/craftsys/msg91-laravel), where we can update the php version if required.

**Comment by ishanAhuja** [comment]
Sure Sudhir, that makes sense. I've changed the PHP version back to `>=7.1`

**Comment by sudkumar** [comment]
@ishanAhuja Thanks for updating. Any particular reason why you have updated guzzle version from ^6.3 to ^6.5 ?

**Comment by ishanAhuja** [comment]
No good reason. I'd initially bumped it to `^7.0.1` but then realised that Laravel's relaxed default might be better and just brought that over.

https://github.com/laravel/framework/blob/8.x/composer.json#L84

**Comment by sudkumar** [comment]
Alright. Thank you.

**Pull request merged**
